name: Build-RMX1901-OrangeFox-recovery
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
   
    steps:
    - name: "Cleanup Environment"
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 11
        
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt install git aria2 python2 -y
        git clone https://gitlab.com/OrangeFox/misc/scripts --depth=1
        cd scripts       
        sudo bash setup/android_build_env.sh
        cd -
        mkdir OrangeFox_sync
        cd OrangeFox_sync
        git clone https://gitlab.com/OrangeFox/sync.git --depth=1
        cd sync/
        ./orangefox_sync.sh --branch 12.1 --path $GITHUB_WORKSPACE/fox_12.1 
    
    - name: Checkout Device Tree
      uses: actions/checkout@v3
      with:
        path: fox_12.1/device/realme/realme_sdm710
    
    - name: Install Android SDK
      run: |
        cp fox_12.1/device/realme/realme_sdm710/.github/patch/SDK.patch scripts
        cd scripts
        git apply ./SDK.patch
        sudo bash setup/install_android_sdk.sh
    
    - name: Build recovery
      run: |
        cd fox_12.1
        source build/envsetup.sh || true
        lunch twrp_realme_sdm710-eng
        mka adbd recoveryimage -j2

    - name: Upload recovery
      uses: actions/upload-artifact@v3
      with:
        name: RMX1901-OFOX-RUI1-UNZIP
        path: |
          fox_12.1/out/target/product/*/Orange*.zip
          fox_12.1/out/target/product/*/Orange*.img
      
 
